export const ui = {
  es: {
    home: 'Inicio', learn: 'Aprender', progress: 'Mis avances', groups: 'Mis grupos', invitations: 'Invitaciones', profile: 'Mi perfil', logout: 'Cerrar sesión', login: 'Entrar con Google', demo: 'Probar modo demo', today: '¿Qué aprenderemos hoy?', continue: 'Continuar aprendiendo', hello: '¡Hola', welcome: 'Bienvenido a Pequeños Escritores', welcomeText: 'Aprende letras, números, colores, formas y palabras con actividades cortas, divertidas y llenas de movimiento.', start: 'Empezar a aprender', lessons: 'Lecciones', attempts: 'Intentos', completed: 'Completadas', score: 'Puntaje', save: 'Guardar cambios', language: 'Idioma', spanish: 'Español', english: 'Inglés', username: 'Nombre de usuario', userId: 'Tu ID para grupos', photo: 'Foto de perfil', uploadPhoto: 'Elegir de mi galería', builtin: 'O elige un personaje', createGroup: 'Crear grupo', groupName: 'Nombre del grupo', create: 'Crear', noGroups: 'Todavía no perteneces a ningún grupo.', inviteMember: 'Invitar miembro', memberId: 'ID del usuario', sendInvite: 'Enviar invitación', members: 'Miembros', assignments: 'Lecciones asignadas', assignLesson: 'Asignar lección', pending: 'Pendiente', accept: 'Aceptar', reject: 'Rechazar', noInvites: 'No tienes invitaciones pendientes.', teacher: 'Docente', student: 'Estudiante', groupProgress: 'Progreso del grupo', play: 'Jugar', listen: 'Escuchar', clear: 'Borrar', done: 'Terminé', next: 'Siguiente', tryAgain: 'Intentar otra vez', great: '¡Muy bien!', keepTrying: '¡Vas aprendiendo!', backLessons: 'Volver a lecciones', signinToSave: 'Inicia sesión para guardar tu progreso en todos tus dispositivos.', demoMode: 'Modo demo activo: conecta Firebase para usar cuentas reales y sincronización en la nube.', loading: 'Cargando…', assignedBy: 'Asignada por', viewGroup: 'Ver grupo', noAssignments: 'No hay lecciones asignadas todavía.', copied: 'ID copiado', copy: 'Copiar', inviteSent: 'Invitación enviada', profileSaved: 'Perfil actualizado', groupCreated: 'Grupo creado', role: 'Rol', lastScore: 'Último puntaje', lessonProgress: 'Progreso por lección', noProgress: 'Aún no hay progreso. ¡Elige una lección y comienza!', classmateProgress: 'Resultados de compañeros', privacyNote: 'Solo mostramos nombre, avatar y progreso dentro del grupo; no se comparte el correo.',
  },
  en: {
    home: 'Home', learn: 'Learn', progress: 'My progress', groups: 'My groups', invitations: 'Invitations', profile: 'My profile', logout: 'Sign out', login: 'Continue with Google', demo: 'Try demo mode', today: 'What will we learn today?', continue: 'Keep learning', hello: 'Hello', welcome: 'Welcome to Little Writers', welcomeText: 'Learn letters, numbers, colors, shapes and words with short, playful and colorful activities.', start: 'Start learning', lessons: 'Lessons', attempts: 'Attempts', completed: 'Completed', score: 'Score', save: 'Save changes', language: 'Language', spanish: 'Spanish', english: 'English', username: 'Username', userId: 'Your group ID', photo: 'Profile picture', uploadPhoto: 'Choose from gallery', builtin: 'Or choose a character', createGroup: 'Create group', groupName: 'Group name', create: 'Create', noGroups: 'You do not belong to any group yet.', inviteMember: 'Invite member', memberId: 'User ID', sendInvite: 'Send invitation', members: 'Members', assignments: 'Assigned lessons', assignLesson: 'Assign lesson', pending: 'Pending', accept: 'Accept', reject: 'Reject', noInvites: 'You have no pending invitations.', teacher: 'Teacher', student: 'Student', groupProgress: 'Group progress', play: 'Play', listen: 'Listen', clear: 'Clear', done: 'Done', next: 'Next', tryAgain: 'Try again', great: 'Great job!', keepTrying: 'You are learning!', backLessons: 'Back to lessons', signinToSave: 'Sign in to save your progress across devices.', demoMode: 'Demo mode is active: connect Firebase to use real accounts and cloud sync.', loading: 'Loading…', assignedBy: 'Assigned by', viewGroup: 'View group', noAssignments: 'No lessons have been assigned yet.', copied: 'ID copied', copy: 'Copy', inviteSent: 'Invitation sent', profileSaved: 'Profile updated', groupCreated: 'Group created', role: 'Role', lastScore: 'Last score', lessonProgress: 'Lesson progress', noProgress: 'No progress yet. Choose a lesson and start!', classmateProgress: 'Classmate results', privacyNote: 'Only name, avatar and learning progress are shown inside the group; email is not shared.',
  },
}

export const tr = (lang, key) => ui[lang]?.[key] ?? ui.es[key] ?? key
